[project]
name = "aabacktest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare>=1.17.61",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "plotly>=5.20.0",
]
